/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VtnJuego.java
 *
 * Created on May 26, 2009, 5:00:39 PM
 */

package ajedrez.cliente;

import ajedrez.entidades.Tablero;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author albertolemus
 */
public class VtnJuego extends javax.swing.JFrame {

    private Jugador jugador;

    public void bloquearJugador()
    {
        jButton1.setEnabled(false);
        cmbPosX.setEnabled(false);
        cmbPosX2.setEnabled(false);
        cmbPosY.setEnabled(false);
        cmbPosY2.setEnabled(false);
    }

    public void desbloquearJugador()
    {
        jButton1.setEnabled(true);
        cmbPosX.setEnabled(true);
        cmbPosX2.setEnabled(true);
        cmbPosY.setEnabled(true);
        cmbPosY2.setEnabled(true);
    }


    public void dibujarTablero(String tab){
        jTextArea1.setText("");
        jTextArea1.setText(tab);
    }


    /** Creates new form VtnJuego */
    public VtnJuego(Jugador j){
        initComponents();
        this.jugador = j;
        jLabel1.setText("Equipo "+j.getColor());
        bloquearJugador();
    }

    public void listo() {
        jLabel3.setText("Jugando");
        desbloquearJugador();
    }

    void mensajeError(String string) {
        //mandar error
        JOptionPane.showMessageDialog(this, string, "Info", JOptionPane.OK_OPTION);
        //System.out.println(string);
        this.desbloquearJugador();

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbPosX = new javax.swing.JComboBox();
        cmbPosY = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbPosX2 = new javax.swing.JComboBox();
        cmbPosY2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipo: ");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        cmbPosX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "c", "d", "e", "f", "g", "h" }));
        jPanel1.add(cmbPosX);

        cmbPosY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel1.add(cmbPosY);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-->");
        jPanel1.add(jLabel2);

        cmbPosX2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "c", "d", "e", "f", "g", "h" }));
        jPanel1.add(cmbPosX2);

        cmbPosY2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel1.add(cmbPosY2);

        jButton1.setText("Mover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Esperando jugador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (this.jugador.mover(this.cmbPosX.getSelectedItem().toString().toCharArray()[0],
                Integer.parseInt(this.cmbPosY.getSelectedItem().toString()),
                this.cmbPosX2.getSelectedItem().toString().toCharArray()[0],
                Integer.parseInt(this.cmbPosY2.getSelectedItem().toString())))
        {
            //Bloqueo al jugador
            this.bloquearJugador();
        }
        else{
            //Mandar mensaje de error, la conexion fallo
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbPosX;
    private javax.swing.JComboBox cmbPosX2;
    private javax.swing.JComboBox cmbPosY;
    private javax.swing.JComboBox cmbPosY2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
